name: Daily Nba Game Prediction Workflow

on:
  schedule:
    - cron: '10 7 * * *'
  workflow_dispatch:{}

permissions:
  contents: write

jobs: 
  run-daily:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # needed so we can commit and push

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependecies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Export secrets
      


        