name: Daily Nba Game Prediction Workflow

on:
  schedule:
    - cron: '10 7 * * *'
  workflow_dispatch:{}

permissions:
  contents: write

jobs: 
  run-daily:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # needed so we can commit and push

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run inference and upload
        env:
          # not secrets, safe to keep inline or repo variables
          MLFLOW_TRACKING_URI: "https://dagshub.com/matJTzimas/NbaGamePrediction.mlflow"
          MLFLOW_TRACKING_USERNAME: "matJTzimas"

          # secrets – stored under GitHub repo → Settings → Secrets and variables → Actions
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
          DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_USER_TOKEN }}
        run: |
          python 

        